### ISSUE TITLE
Manual

### ISSUE THREAD

**Issue by gabimjesus** [sromku/memory-game#2]
It would be very helpful if we have a manual with instructions about how to compile and run the project.

**Comment by sromku** [comment]
@gabimjesus nothing special is needed. Just open this project from Android studio and run.

**Comment by gabimjesus** [comment]
Does it work only using Android studio? How about an IDE like Netbeans?

**Comment by sromku** [comment]
It works only with Android studio. There is plenty of built in stuff that had to be used for project to be compiled and run. (like resources class automatic generation, gradle support, xmls parsing and bunch of other must stuff).
