### ISSUE TITLE
game stop when I click play

### ISSUE THREAD

**Issue by HarryF514** [sromku/memory-game#5]
I run this game in genymotion, Samsung Galaxy S4 API 19. the game stop after I click play. 

I will try to add screenshot later. or test in a real device

Update:

I tried with API 23 and it is working

**Comment by sromku** [comment]
Hi @harryyuanfeng . Can you share the stacktrace so we can know what might be the reason for this? Thanks

**Comment by HarryF514** [comment]
never mind. solve this problem after I re-download the virtual device. now game is working in Samsung Galaxy S4 API 19. May close this issue.

**Comment by sromku** [comment]
sure, thanks for update.
