### ISSUE TITLE
Feature suggestion : Best Time for stage

### ISSUE THREAD

**Issue by Dimitrees** [sromku/memory-game#6]
Hello!

Great job with the game, looks nice and simple. I have on suggestion to make, regarding the difficulty selection screen. How would you like it that the best time for each difficulty and stage would appear under the stars label? Stars don't make it completely understandable how well someone has performed in each stage. However time does. So this is my suggestion on how it would look. 

![image](https://user-images.githubusercontent.com/15691073/30271715-fa954fe2-96f9-11e7-8601-9f8cec76e285.png)

Keep in mind that this is just a quick edit to demonstrate my idea and it is not the final view of the screen. Let me know what you think. 

Thank you, 
Dimitris

**Comment by sromku** [comment]
I very like the idea and this very nice addition! 👍 Let's add it :)

**Comment by Dimitrees** [comment]
Thank you, I am already working on it. I hope I'll have a PR soon. :)

**Comment by sromku** [comment]
https://github.com/snatik/memory-game/pull/7
