### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by nooraldin** [sromku/memory-game#9]
**Exception java.lang.RuntimeException: Unable to start activity ComponentInfo{com.memorygame/com.memorygame.MainActivity}: java.lang.NullPointerException: Attempt to read from field 'com.memorygame.model.BoardConfiguration com.memorygame.model.Game.boardConfiguration' on a null object reference**

android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2695)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2769)
android.app.ActivityThread.handleRelaunchActivity (ActivityThread.java:4378)
android.app.ActivityThread.access$1000 (ActivityThread.java:177)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1436)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:135)
android.app.ActivityThread.main (ActivityThread.java:5910)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1405)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1200)
arrow_drop_down
**Caused by java.lang.NullPointerException: Attempt to read from field 'com.memorygame.model.BoardConfiguration com.memorygame.model.Game.boardConfiguration' on a null object reference**
com.memorygame.fragments.GameFragment.buildBoard (GameFragment.java:76)
com.memorygame.fragments.GameFragment.onCreateView (GameFragment.java:48)
android.support.v4.app.Fragment.performCreateView (Fragment.java:2354)
android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1419)
android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState (FragmentManager.java:1740)
android.support.v4.app.FragmentManagerImpl.moveToState (FragmentManager.java:1809)
android.support.v4.app.FragmentManagerImpl.dispatchStateChange (FragmentManager.java:3217)
android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated (FragmentManager.java:3171)
android.support.v4.app.FragmentController.dispatchActivityCreated (FragmentController.java:192)
android.support.v4.app.FragmentActivity.onStart (FragmentActivity.java:560)
android.app.Instrumentation.callActivityOnStart (Instrumentation.java:1248)
android.app.Activity.performStart (Activity.java:6213)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2658)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2769)
android.app.ActivityThread.handleRelaunchActivity (ActivityThread.java:4378)
android.app.ActivityThread.access$1000 (ActivityThread.java:177)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1436)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:135)
android.app.ActivityThread.main (ActivityThread.java:5910)
java.lang.reflect.Method.invoke (Method.java)
java.lang.reflect.Method.invoke (Method.java:372)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1405)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1200)

**Comment by sromku** [comment]
@nooraldin it crashes on line 76 of GameFragment in your case. This line doesn't have any code on master branch here: https://github.com/snatik/memory-game/blob/master/app/src/main/java/com/snatik/matches/fragments/GameFragment.java#L76.
It means that you changed the code. Without seeing your changes it's hard to know what causes this null exception. The only thing that I can tell is that in `Game game = Shared.engine.getActiveGame();` -> game=null. 

1. Explain the full scenario of what you did that made you getting this exception.
2. Check why active game is not initialized.

**Comment by nooraldin** [comment]
# Big Thanks For You

`	private void buildBoard() {
		Game game = Shareds.engines.getActiveGame();
		int time = game.boardConfiguration.time;  
		setTime(time);
		mBoardView.setBoard(game);
		startClock(time);
	}`
	
line 76 of GameFragment is 	((  mBoardView.setBoard(game);  ))

**Comment by sromku** [comment]
Then the `mBoardView` is null. Make sure to init the view. Like here: https://github.com/snatik/memory-game/blob/master/app/src/main/java/com/snatik/matches/fragments/GameFragment.java#L40

**Comment by nooraldin** [comment]
public class GameFragment extends BaseFragment {

	private BoardView mBoardView;
	private TextView mTime;
	private ImageView mTimeImage;
	private NativeExpressAdView  AdView;

	@Override
	public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
		ViewGroup view = (ViewGroup) inflater.inflate(R.layout.game_fragment, container, false);
		view.setClipChildren(false);
		((ViewGroup)view.findViewById(R.id.ga_bo)).setClipChildren(false);
		mTime = (TextView) view.findViewById(R.id.time_bar_text);
		mTimeImage = (ImageView) view.findViewById(R.id.ti_im);
		FontLoader.setTypeface(Shareds.context, new TextView[] {mTime}, Font.GR);
		mBoardView = BoardView.fromXml(getActivity().getApplicationContext(), view);
		FrameLayout frameLayout = (FrameLayout) view.findViewById(R.id.game_container);
		frameLayout.addView(mBoardView);
		frameLayout.setClipChildren(false);

		// build board
		buildBoard();
		Shareds.eventBus.listen(FlipDownCardsEvent.TYPE, this);
		Shareds.eventBus.listen(HidePairCardsEvent.TYPE, this);
		Shareds.eventBus.listen(GameWonEvent.TYPE, this);




		AdView= (NativeExpressAdView)view.findViewById(R.id.adView5);
		AdRequest request = new AdRequest.Builder().build();
		AdView.loadAd(request);




		return view;
	}
	
	@Override
	public void onDestroy() {
		Shareds.eventBus.unlisten(FlipDownCardsEvent.TYPE, this);
		Shareds.eventBus.unlisten(HidePairCardsEvent.TYPE, this);
		Shareds.eventBus.unlisten(GameWonEvent.TYPE, this);
		super.onDestroy();
	}

	private void buildBoard() {
		Game game = Shareds.engines.getActiveGame();
		int time = game.boardConfiguration.time;
		setTime(time);
		mBoardView.setBoard(game);
		
		startClock(time);
	}
	
	private void setTime(int time) {
		int min = time / 60;
		int sec = time - min*60;
		mTime.setText(" " + String.format("%02d", min) + ":" + String.format("%02d", sec));
	}

	private void startClock(int sec) {
		Clock clock = Clock.getInstance();
		clock.startTimer(sec*1000, 1000, new OnTimerCount() {
			
			@Override
			public void onTick(long millisUntilFinished) {
				setTime((int) (millisUntilFinished/1000));
			}
			
			@Override
			public void onFinish() {
				setTime(0);
			}
		});
	}

	@Override
	public void onEvent(GameWonEvent event) {
		mTime.setVisibility(View.GONE);
		mTimeImage.setVisibility(View.GONE);
		PopupManager.showPopupWon(event.gameState);
	}

	@Override
	public void onEvent(FlipDownCardsEvent event) {
		mBoardView.flipDownAll();
	}

	@Override
	public void onEvent(HidePairCardsEvent event) {
		mBoardView.hideCards(event.id1, event.id2);
	}

}

**Comment by sromku** [comment]
What line it crashes?

**Comment by nooraldin** [comment]
Caused by java.lang.NullPointerException:
com.memorygame.fragments.GameFragment.buildBoard (GameFragment.java:76)
com.memorygame.fragments.GameFragment.onCreateView (GameFragment.java:48)

**Comment by nooraldin** [comment]
i think these line

**Comment by sromku** [comment]
@nooraldin, to help you investigate issues of this kind please:

1. Share **full** stacktrace.
2. Share the full class with the **line numbers**, otherwise I don't have a light clue what is the line number you are talking about.
3. Describe the flow. For example: *Opened the app -> Selected theme-> Started game and then it crashed.*

**Comment by nooraldin** [comment]
### thank you for replay and i am sorry for forget number

i will share all class ..

in androidstudio didn't have any problem this crashes come from Firebase (crash reporting)

and had another crash reporting 

`Exception java.lang.NullPointerException: Attempt to read from field 'int com.memorygame.model.GameState.achievedStars' on a null object reference
com.memorygame.engine.Engines.onEvent (Engines.java:129)
com.memorygame.events.ui.NextGameEvent.fire (NextGameEvent.java:15)
com.memorygame.events.EventBus.notify (EventBus.java:57)
com.memorygame.ui.PopupWonView$2.onClick (PopupWonView.java:76)`

**Comment by nooraldin** [comment]
## i cant copy with line number 
ı made mark /////76 + ///////48 beside the line



public class GameFragment extends BaseFragment {

	private BoardView mBoardView;
	private TextView mTime;
	private ImageView mTimeImage;
	private NativeExpressAdView  AdView;

	@Override
	public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
		ViewGroup view = (ViewGroup) inflater.inflate(R.layout.game_fragment, container, false);
		view.setClipChildren(false);
		((ViewGroup)view.findViewById(R.id.ga_bo)).setClipChildren(false);
		mTime = (TextView) view.findViewById(R.id.time_bar_text);
		mTimeImage = (ImageView) view.findViewById(R.id.ti_im);
		FontLoader.setTypeface(Shareds.context, new TextView[] {mTime}, Font.GR);
		mBoardView = BoardView.fromXml(getActivity().getApplicationContext(), view);
		FrameLayout frameLayout = (FrameLayout) view.findViewById(R.id.game_container);
		frameLayout.addView(mBoardView);
		frameLayout.setClipChildren(false);

		// build board
		buildBoard();                             ////////////////////////////  48  line
		Shareds.eventBus.listen(FlipDownCardsEvent.TYPE, this);
		Shareds.eventBus.listen(HidePairCardsEvent.TYPE, this);
		Shareds.eventBus.listen(GameWonEvent.TYPE, this);




		AdView= (NativeExpressAdView)view.findViewById(R.id.adView5);
		AdRequest request = new AdRequest.Builder().build();
		AdView.loadAd(request);




		return view;
	}
	
	@Override
	public void onDestroy() {
		Shareds.eventBus.unlisten(FlipDownCardsEvent.TYPE, this);
		Shareds.eventBus.unlisten(HidePairCardsEvent.TYPE, this);
		Shareds.eventBus.unlisten(GameWonEvent.TYPE, this);
		super.onDestroy();
	}

	private void buildBoard() {
		Game game = Shareds.engines.getActiveGame();
		int time = game.boardConfiguration.time;         ////////////////////////////  76  line
		setTime(time);
		 mBoardView.setBoard(game);  
		
		startClock(time);
	}
	
	private void setTime(int time) {
		int min = time / 60;
		int sec = time - min*60;
		mTime.setText(" " + String.format("%02d", min) + ":" + String.format("%02d", sec));
	}

	private void startClock(int sec) {
		Clock clock = Clock.getInstance();
		clock.startTimer(sec*1000, 1000, new OnTimerCount() {
			
			@Override
			public void onTick(long millisUntilFinished) {
				setTime((int) (millisUntilFinished/1000));
			}
			
			@Override
			public void onFinish() {
				setTime(0);
			}
		});
	}

	@Override
	public void onEvent(GameWonEvent event) {
		mTime.setVisibility(View.GONE);
		mTimeImage.setVisibility(View.GONE);
		PopupManager.showPopupWon(event.gameState);
	}

	@Override
	public void onEvent(FlipDownCardsEvent event) {
		mBoardView.flipDownAll();
	}

	@Override
	public void onEvent(HidePairCardsEvent event) {
		mBoardView.hideCards(event.id1, event.id2);
	}

}
`

**Comment by nooraldin** [comment]
public class Engines extends EventObserverAdapter {

    private static Engines mInstance = null;
    private Game mPlayingGame = null;
    private int mFlippedId = -1;
    private int mToFlip = -1;
    private ScreenControllers mScreenControllers;
    private Theme mSelectedTheme;
    private ImageView mBackgroundImage;
    private Handler mHandler;

    private Engines() {
        mScreenControllers = ScreenControllers.getInstance();
        mHandler = new Handler();
    }

    public static Engines getInstance() {
        if (mInstance == null) {
            mInstance = new Engines();
        }
        return mInstance;
    }

    public void start() {
        Shareds.eventBus.listen(DifficultySelectedEvent.TYPE, this);
        Shareds.eventBus.listen(FlipCardEvent.TYPE, this);
        Shareds.eventBus.listen(StartEvent.TYPE, this);
        Shareds.eventBus.listen(ThemeSelectedEvent.TYPE, this);
        Shareds.eventBus.listen(BackGameEvent.TYPE, this);
        Shareds.eventBus.listen(NextGameEvent.TYPE, this);
        Shareds.eventBus.listen(ResetBackgroundEvent.TYPE, this);
    }

    public void stop() {
        mPlayingGame = null;
        mBackgroundImage.setImageDrawable(null);
        mBackgroundImage = null;
        mHandler.removeCallbacksAndMessages(null);
        mHandler = null;

        Shareds.eventBus.unlisten(DifficultySelectedEvent.TYPE, this);
        Shareds.eventBus.unlisten(FlipCardEvent.TYPE, this);
        Shareds.eventBus.unlisten(StartEvent.TYPE, this);
        Shareds.eventBus.unlisten(ThemeSelectedEvent.TYPE, this);
        Shareds.eventBus.unlisten(BackGameEvent.TYPE, this);
        Shareds.eventBus.unlisten(NextGameEvent.TYPE, this);
        Shareds.eventBus.unlisten(ResetBackgroundEvent.TYPE, this);

        mInstance = null;
    }

    @Override
    public void onEvent(ResetBackgroundEvent event) {
        Drawable drawable = mBackgroundImage.getDrawable();
        if (drawable != null) {
            ((TransitionDrawable) drawable).reverseTransition(2000);
        } else {
            new AsyncTask<Void, Void, Bitmap>() {

                @Override
                protected Bitmap doInBackground(Void... params) {
                    Bitmap bitmap = Utils.scaleDown(R.drawable.back_graound, Utils.screenWidth(), Utils.screenHeight());
                    return bitmap;
                }

                protected void onPostExecute(Bitmap bitmap) {
                    mBackgroundImage.setImageBitmap(bitmap);
                };

            }.execute();
        }
    }

    @Override
    public void onEvent(StartEvent event) {
        mScreenControllers.openScreen(Screen.THEME_SELECT);
    }

    @Override
    public void onEvent(NextGameEvent event) {
        PopupManager.closePopup();                ////////////////127                                                                      
        int difficulty = mPlayingGame.boardConfiguration.difficulty;
        if (mPlayingGame.gameState.achievedStars == 3 && difficulty < 6) {                  ////////////////129
            difficulty++;
        }
        Shareds.eventBus.notify(new DifficultySelectedEvent(difficulty));
    }

    @Override
    public void onEvent(BackGameEvent event) {
        PopupManager.closePopup();
        mScreenControllers.openScreen(Screen.DIFFICULTY);
    }

    @Override
    public void onEvent(ThemeSelectedEvent event) {
        mSelectedTheme = event.theme;
        mScreenControllers.openScreen(Screen.DIFFICULTY);
        AsyncTask<Void, Void, TransitionDrawable> task = new AsyncTask<Void, Void, TransitionDrawable>() {

            @Override
            protected TransitionDrawable doInBackground(Void... params) {
                Bitmap bitmap = Utils.scaleDown(R.drawable.back_back, Utils.screenWidth(), Utils.screenHeight());
                Bitmap backgroundImage = Themes.getBackgroundImage(mSelectedTheme);
                backgroundImage = Utils.crop(backgroundImage, Utils.screenHeight(), Utils.screenWidth());
                Drawable backgrounds[] = new Drawable[2];
                backgrounds[0] = new BitmapDrawable(Shareds.context.getResources(), bitmap);
                backgrounds[1] = new BitmapDrawable(Shareds.context.getResources(), backgroundImage);
                TransitionDrawable crossfader = new TransitionDrawable(backgrounds);
                return crossfader;
            }

            @Override
            protected void onPostExecute(TransitionDrawable result) {
                super.onPostExecute(result);
                mBackgroundImage.setImageDrawable(result);
                result.startTransition(2000);
            }
        };
        task.execute();
    }

    @Override
    public void onEvent(DifficultySelectedEvent event) {
        mFlippedId = -1;
        mPlayingGame = new Game();
        mPlayingGame.boardConfiguration = new BoardConfiguration(event.difficulty);
        mPlayingGame.theme = mSelectedTheme;
        mToFlip = mPlayingGame.boardConfiguration.numTiles;

        // arrange board
        arrangeBoard();

        // start the screen
        mScreenControllers.openScreen(Screen.GAME);
    }

    private void arrangeBoard() {
        BoardConfiguration boardConfiguration = mPlayingGame.boardConfiguration;
        BoardArrangment boardArrangment = new BoardArrangment();


        List<Integer> ids = new ArrayList<Integer>();
        for (int i = 0; i < boardConfiguration.numTiles; i++) {
            ids.add(i);
        }

        Collections.shuffle(ids);


        List<String> tileImageUrls = mPlayingGame.theme.tileImageUrls;
        Collections.shuffle(tileImageUrls);
        boardArrangment.pairs = new HashMap<Integer, Integer>();
        boardArrangment.tileUrls = new HashMap<Integer, String>();
        int j = 0;
        for (int i = 0; i < ids.size(); i++) {
            if (i + 1 < ids.size()) {

                boardArrangment.pairs.put(ids.get(i), ids.get(i + 1));
                boardArrangment.pairs.put(ids.get(i + 1), ids.get(i));
                boardArrangment.tileUrls.put(ids.get(i), tileImageUrls.get(j));
                boardArrangment.tileUrls.put(ids.get(i + 1), tileImageUrls.get(j));
                i++;
                j++;
            }
        }

        mPlayingGame.boardArrangment = boardArrangment;
    }

    @Override
    public void onEvent(FlipCardEvent event) {
        int id = event.id;
        if (mFlippedId == -1) {
            mFlippedId = id;
        } else {
            if (mPlayingGame.boardArrangment.isPair(mFlippedId, id)) {
                Shareds.eventBus.notify(new HidePairCardsEvent(mFlippedId, id), 1000);
                mHandler.postDelayed(new Runnable() {

                    @Override
                    public void run() {
                        Mus.playCorrent();
                    }
                }, 1000);
                mToFlip -= 2;
                if (mToFlip == 0) {
                    int passedSeconds = (int) (Clock.getInstance().getPassedTime() / 1000);
                    Clock.getInstance().pause();
                    int totalTime = mPlayingGame.boardConfiguration.time;
                    GameState gameState = new GameState();
                    mPlayingGame.gameState = gameState;
                    gameState.remainedSeconds = totalTime - passedSeconds;
                    if (passedSeconds <= totalTime / 2) {
                        gameState.achievedStars = 3;
                    } else if (passedSeconds <= totalTime - totalTime / 5) {
                        gameState.achievedStars = 2;
                    } else if (passedSeconds < totalTime) {
                        gameState.achievedStars = 1;
                    } else {
                        gameState.achievedStars = 0;
                    }

                    gameState.achievedScore = mPlayingGame.boardConfiguration.difficulty * gameState.remainedSeconds * mPlayingGame.theme.id;
                    Memo.save(mPlayingGame.theme.id, mPlayingGame.boardConfiguration.difficulty, gameState.achievedStars);
                    Shareds.eventBus.notify(new GameWonEvent(gameState), 1200);
                }
            } else {
                Shareds.eventBus.notify(new FlipDownCardsEvent(), 1000);
                mHandler.postDelayed(new Runnable() {

                    @Override
                    public void run() {
                        Mus.playwrong();
                    }
                }, 1000);
            }
            mFlippedId = -1;

        }
    }

    public Game getActiveGame() {
        return mPlayingGame;
    }

    public Theme getSelectedTheme() {
        return mSelectedTheme;
    }

    public void setBackgroundImageView(ImageView backgroundImage) {
        mBackgroundImage = backgroundImage;
    }
}

**Comment by nooraldin** [comment]
# i hope you can help me
thank you

**Comment by sromku** [comment]
1. `gameState` is null. The only place we init it is only after fully finishing the game. Here: https://github.com/snatik/memory-game/blob/master/app/src/main/java/com/snatik/matches/engine/Engine.java#L242. 
2. You can fix it by initializing GameState after the line: `mPlayingGame = new Game();`. Something like: `mPlayingGame.gameState = new GameState()`.

Beside this, I can't help you with firebase errors. You have changed the code of the app, and I can support and fix if you refer only to this code base.

**Comment by nooraldin** [comment]
thank you
